const data = {
  getData() {
    return [
      {
        id: 10001,
        supervisor_id: "sp10001",
        name: "Task Name 01",
        category: "Category A",
        location: "Block A",
        staffs: [{ id: "S1001" }, { id: "S1002" }, { id: "S1003" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10002,
        supervisor_id: "sp10002",
        name: "Task Name 02",
        category: "Category B",
        location: "Block B",
        staffs: [{ id: "S1004" }, { id: "S1005" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10003,
        supervisor_id: "sp10003",
        name: "Task Name 03",
        category: "Category C",
        location: "Block C",
        staffs: [{ id: "S1006" }, { id: "S1007" }, { id: "S1008" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10004,
        supervisor_id: "sp10004",
        name: "Task Name 04",
        category: "Category A",
        location: "Block D",
        staffs: [{ id: "S1009" }, { id: "S1010" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10005,
        supervisor_id: "sp10005",
        name: "Task Name 05",
        category: "Category B",
        location: "Block E",
        staffs: [{ id: "S1011" }, { id: "S1012" }, { id: "S1013" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10006,
        supervisor_id: "sp10006",
        name: "Task Name 06",
        category: "Category C",
        location: "Block F",
        staffs: [{ id: "S1014" }, { id: "S1015" }, { id: "S1016" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10007,
        supervisor_id: "sp10007",
        name: "Task Name 07",
        category: "Category A",
        location: "Block G",
        staffs: [{ id: "S1017" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10008,
        supervisor_id: "sp10008",
        name: "Task Name 08",
        category: "Category B",
        location: "Block H",
        staffs: [{ id: "S1018" }, { id: "S1019" }, { id: "S1020" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10009,
        supervisor_id: "sp10009",
        name: "Task Name 09",
        category: "Category C",
        location: "Block I",
        staffs: [{ id: "S1021" }, { id: "S1022" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10010,
        supervisor_id: "sp10010",
        name: "Task Name 10",
        category: "Category A",
        location: "Block J",
        staffs: [{ id: "S1023" }, { id: "S1024" }, { id: "S1025" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10011,
        supervisor_id: "sp10011",
        name: "Task Name 11",
        category: "Category B",
        location: "Block K",
        staffs: [{ id: "S1026" }, { id: "S1027" }, { id: "S1028" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10012,
        supervisor_id: "sp10012",
        name: "Task Name 12",
        category: "Category C",
        location: "Block L",
        staffs: [{ id: "S1029" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10013,
        supervisor_id: "sp10013",
        name: "Task Name 13",
        category: "Category A",
        location: "Block M",
        staffs: [{ id: "S1030" }, { id: "S1031" }, { id: "S1032" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10014,
        supervisor_id: "sp10014",
        name: "Task Name 14",
        category: "Category B",
        location: "Block N",
        staffs: [{ id: "S1033" }, { id: "S1034" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10015,
        supervisor_id: "sp10015",
        name: "Task Name 15",
        category: "Category C",
        location: "Block O",
        staffs: [{ id: "S1035" }, { id: "S1036" }, { id: "S1037" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10016,
        supervisor_id: "sp10016",
        name: "Task Name 16",
        category: "Category A",
        location: "Block P",
        staffs: [{ id: "S1038" }, { id: "S1039" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10017,
        supervisor_id: "sp10017",
        name: "Task Name 17",
        category: "Category B",
        location: "Block Q",
        staffs: [{ id: "S1040" }, { id: "S1041" }, { id: "S1042" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10018,
        supervisor_id: "sp10018",
        name: "Task Name 18",
        category: "Category C",
        location: "Block R",
        staffs: [{ id: "S1043" }, { id: "S1044" }, { id: "S1045" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10019,
        supervisor_id: "sp10019",
        name: "Task Name 19",
        category: "Category A",
        location: "Block S",
        staffs: [{ id: "S1046" }, { id: "S1047" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10020,
        supervisor_id: "sp10020",
        name: "Task Name 20",
        category: "Category B",
        location: "Block T",
        staffs: [{ id: "S1048" }, { id: "S1049" }, { id: "S1050" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10021,
        supervisor_id: "sp10021",
        name: "Task Name 21",
        category: "Category C",
        location: "Block U",
        staffs: [{ id: "S1051" }, { id: "S1052" }, { id: "S1053" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10022,
        supervisor_id: "sp10022",
        name: "Task Name 22",
        category: "Category A",
        location: "Block V",
        staffs: [{ id: "S1054" }, { id: "S1055" }, { id: "S1056" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10023,
        supervisor_id: "sp10023",
        name: "Task Name 23",
        category: "Category B",
        location: "Block W",
        staffs: [{ id: "S1057" }, { id: "S1058" }, { id: "S1059" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10024,
        supervisor_id: "sp10024",
        name: "Task Name 24",
        category: "Category C",
        location: "Block X",
        staffs: [{ id: "S1060" }, { id: "S1061" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10025,
        supervisor_id: "sp10025",
        name: "Task Name 25",
        category: "Category A",
        location: "Block Y",
        staffs: [{ id: "S1062" }, { id: "S1063" }, { id: "S1064" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10026,
        supervisor_id: "sp10026",
        name: "Task Name 26",
        category: "Category B",
        location: "Block Z",
        staffs: [{ id: "S1065" }, { id: "S1066" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10027,
        supervisor_id: "sp10027",
        name: "Task Name 27",
        category: "Category C",
        location: "Block AA",
        staffs: [{ id: "S1067" }, { id: "S1068" }, { id: "S1069" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10028,
        supervisor_id: "sp10028",
        name: "Task Name 28",
        category: "Category A",
        location: "Block BB",
        staffs: [{ id: "S1070" }, { id: "S1071" }],
        status: "Ongoing",
        est: 3,
        remarks: "Not Yet Added",
      },
      {
        id: 10029,
        supervisor_id: "sp10029",
        name: "Task Name 29",
        category: "Category B",
        location: "Block CC",
        staffs: [{ id: "S1072" }, { id: "S1073" }, { id: "S1074" }],
        status: "Completed",
        est: 3,
        remarks: "Added",
      },
      {
        id: 10030,
        supervisor_id: "sp10030",
        name: "Task Name 30",
        category: "Category C",
        location: "Block DD",
        staffs: [{ id: "S1075" }, { id: "S1076" }, { id: "S1077" }],
        status: "Pending",
        est: 3,
        remarks: "Not Yet Added",
      },
    ];
  },
  getTasks() {
    return Promise.resolve(this.getData());
  },
};

export default data;
